### PR TITLE
Migrate existing functionality to MVVM

### PR DESCRIPTION
**Pull request by andrei-ivanovici**
I've migrated  the existing working screens to MVVM . Please let me know if there are any questions :)

### CODE REVIEW

**Comment by poma** [comment]
I need some time to review this. Probably will be able to get to it tomorrow.

**Comment by andrei-ivanovici** [comment]
I will fix the merge and there is a small  bug on the detailed stats screen. In the meantime, please review the overall changes.  I don't think  I  need to change major anymore. I will address the bug  and the merge issue in the following days

**Comment by andrei-ivanovici** [comment]
Fixed merge issues. should be fine now. I also tested it in a  couple of games and everything seems in order. Please try it yourself before merging.

**Comment by poma** [comment]
I merged this PR as a separate commit d63e0e5f because I had to make a few changes:
1. All line endings should be in Unix style (`\n`) as per git guidelines
2. I don't see any reason to duplicate settings as ViewModel properties

By the way it looks like tab indentation tends to create a mess because I still see spaces in a few files. I think I will convert everything to spaces to keep indentation consistent. I've already configured my scripts that convert between tabs and spaces on checkin-checkout so I will continue to work with tabs locally. Wanted to make sure that you don't have any unmerged changes to avoid merge conflicts.

**Comment by andrei-ivanovici** [comment]
Hi. Thank you for  reviewing the  code  and for  taking the time to merge it. I will do my best to make sure there are no  spacing conflicts in the future.  I'd also want to send my apologies for not replying for this long. I had a really hard period at work  in the past month
 As for your second point, I   tend  to disagree. One  source of problems that I've seen throughout the projects that I was involved with was  global state, and that is what our settings object is. As you probably noticed,  I'm always passing the setting object  in the  view-model and update it as needed. My plan was to further refine this and use an interface rather than  the settings object itself. The motivation for  this  is that it improves the testability of the code. I'd  strongly suggest that we start introducing some unit tests soon, as it will allow us to catch a lot of bugs before releasing a new version in the wild and it will greatly  help us with refactoring and improve the codebase as the project grows. 
One good start is to try and  replace all tight coupled dependencies with abstractions and  use IOC (I'm talking about the inversion of control pattern, not  DI containers) to provide them to our components.

We can pick this up in a different thread :)

**Pull request closed without merging**
